USE covid_db;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT confirmed_cases, deaths FROM covid_cases WHERE country = 'India' AND report_date = '2023-03-01';
ROLLBACK;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT confirmed_cases, deaths FROM covid_cases WHERE country = 'India' AND report_date = '2023-03-01';
SELECT confirmed_cases, deaths FROM covid_cases WHERE country = 'India' AND report_date = '2023-03-01';
COMMIT;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT confirmed_cases FROM covid_cases WHERE country = 'India' AND report_date = '2023-03-01';
SELECT confirmed_cases FROM covid_cases WHERE country = 'India' AND report_date = '2023-03-01';
COMMIT;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT COUNT(*) FROM covid_cases WHERE country = 'India';
SELECT COUNT(*) FROM covid_cases WHERE country = 'India';
COMMIT;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW SESSION VARIABLES LIKE 'transaction_isolation';
